[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18.17.0"
  NPM_FLAGS = "--legacy-peer-deps --no-optional"
  NEXT_WEBPACK_USEPOLLING = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    enable = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[functions]
  node_bundler = "esbuild"